CC     = gcc
CFLAGS = -std=gnu99 -Wall -Wextra -O3 -g
LIB    = `pkg-config --cflags --libs sndfile` -lm
OBJ    = pulse_height_hist.o
PROG   = pulse_height_hist

all:	$(OBJ)
	$(CC) $(LIB) $(OBJ) -o $(PROG)

pulse_height_hist.o: pulse_height_hist.c
	$(CC) $(CFLAGS) -c pulse_height_hist.c

clean:
	rm -f pulse_height_hist $(OBJ)
